- name: Grep local ip address
  shell: "ifconfig -a eth1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'"
  register: local_ip

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ local_ip.stdout }}
    create: yes

- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  ignore_errors: true

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -rf /etc/kubernetes/kubelet.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config
    - chown vagrant:vagrant /var/lib/kubelet
