- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  ignore_errors: true

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -rf /etc/kubernetes/kubelet.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config
    - chown vagrant:vagrant /var/lib/kubelet
